learning_rate: 0.001  # placeholder
batch_size: 32  # placeholder
dropout_rate: 0.5  # placeholder
optimizer: 'adam'  # placeholder
weight_decay: 0.0001  # placeholder
num_epochs: 20  # placeholder
patience: 5  # placeholder
num_layers_to_unfreeze: 1  # placeholder 