# Best Model Configuration for Pneumonia CNN

kernel_size: 3
dropout_rate: 0.4764458724458618
conv1_channels: 32
conv2_channels: 64
fc1_units: 64
learning_rate: 0.0024874243926502936
batch_size: 256
optimizer: rmsprop
weight_decay: 1.2517974793369209e-05
num_epochs: 30
early_stopping_patience: 5
early_stopping_delta: 0.001 